G1/PizzaApp/PizzaWebApp/PizzaWebApp/Models/OrderViewModel.cs
namespace PizzaWebApp.Models
{
    public class OrderViewModel
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Note { get; set; }
        public decimal TotalPrice { get; set; }
        public List<OrderItemViewModel> Items { get; set; }

        public OrderViewModel()
        {
            Items = new List<OrderItemViewModel>();
        }
    }
}

G1/PizzaApp/PizzaWebApp/PizzaWebApp/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using PizzaWebApp.DomainModels;
using PizzaWebApp.Helpers;
using PizzaWebApp.Mappers;
using PizzaWebApp.Models;
using PizzaWebApp.Storage;

namespace PizzaWebApp.Controllers
{
    public class OrderController : Controller
    {
        public IActionResult Index()
        {
            var orders = PizzaDb.Orders.Select(x => x.ToViewModel()).ToList();
            return View(orders);
        }

        public IActionResult CreateOrder()
        {
            return View(new OrderViewModel());
        }

        [HttpPost]
        public IActionResult Save(OrderViewModel model)
        {
            var order = new Order(CommonHelper.GetRandomId(), model.Address, model.PhoneNumber, model.Note, new List<OrderItem>());

            PizzaDb.Orders.Add(order);

            return RedirectToAction("Details", new { id = order.Id });
        }

        public IActionResult Details(int id)
        {
            var order = PizzaDb.Orders.FirstOrDefault(x => x.Id == id);

            if (order == null)
            {
                throw new Exception("Order not found");
            }

            return View(order.ToViewModel());
        }

        public IActionResult Delete(int id)
        {
            var existingOrder = PizzaDb.Orders.FirstOrDefault(x => x.Id == id);

            if (existingOrder == null)
            {
                throw new Exception($"Order with id {id} does not exist");
            }

            PizzaDb.Orders.Remove(existingOrder);

            return RedirectToAction("Index");
        }
    }
}

G1/PizzaApp/PizzaWebApp/PizzaWebApp/Controllers/OrderItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PizzaWebApp.DomainModels;
using PizzaWebApp.Helpers;
using PizzaWebApp.Models;
using PizzaWebApp.Storage;

namespace PizzaWebApp.Controllers
{
    public class OrderItemController : Controller
    {
        public IActionResult CreateOrderItem(int id)
        {
            ViewBag.MenuItems = PizzaDb.MenuItems.Select(x => new SelectListItem(x.ToString(), x.Id.ToString()));

            var orderItem = new OrderItemViewModel()
            {
                OrderId = id
            };

            return View(orderItem);
        }

        [HttpPost]
        public IActionResult Save(OrderItemViewModel model)
        {
            var order = PizzaDb.Orders.FirstOrDefault(x => x.Id == model.OrderId);

            if(order == null)
            {
                throw new Exception($"Order does not exist");
            }

            var menuItem = PizzaDb.MenuItems.FirstOrDefault(x => x.Id == model.MenuItem.Id);

            if (menuItem == null)
            {
                throw new Exception($"Menu item does not exist");
            }

            if(model.Quantity <= 0)
            {
                throw new Exception($"Quantity must be grater than 0");
            }

            var orderItem = new OrderItem(CommonHelper.GetRandomId(), menuItem, model.Quantity);

            order.OrderItems.Add(orderItem);

            return RedirectToAction("Details", "Order", new { id = model.OrderId });
        }

        public IActionResult Delete(int id)
        {
            var existingOrder = PizzaDb.Orders.FirstOrDefault(x => x.OrderItems.Any(y => y.Id == id));

            if (existingOrder == null)
            {
                throw new Exception($"Order that contains order item with {id} does not exist");
            }

            var existingOrderItem = existingOrder.OrderItems.First(x => x.Id == id);

            existingOrder.OrderItems.Remove(existingOrderItem);

            return RedirectToAction("Details", "Order", new { id = existingOrder.Id });
        }
    }
}

G1/PizzaApp/PizzaWebApp/PizzaWebApp/Views/Order/CreateOrder.cshtml
@model OrderViewModel

<form method="post" asp-action="Save">
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber"></label>
        <input asp-for="PhoneNumber" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Note"></label>
        <input asp-for="Note" class="form-control" />
    </div>
    <hr />
    <input type="submit" class="btn btn-primary float-right" value="Save" />
</form>

G1/PizzaApp/PizzaWebApp/PizzaWebApp/Views/Order/Details.cshtml
@using System.Globalization;
@model OrderViewModel

<div>
    <span class="col-6">
        <h3>@Model.Address</h3>
        <h6>@Model.PhoneNumber</h6>
        <h6>@Model.Note</h6>
        <h4>@Model.TotalPrice.ToString("C", CultureInfo.CreateSpecificCulture("mk-MK"))</h4>
    </span>
</div>

<a asp-action="CreateOrderItem" asp-controller="OrderItem" asp-route-id="@Model.Id" class="btn btn-primary">Add new pizza</a>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Pizza</th>
      <th scope="col">Quantity</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
        @for (var i = 0; i < Model.Items.Count; i++)
        {            
                <tr>
                  <th scope="row">@(i + 1)</th>
                  <td>@Model.Items[i].MenuItem.ToString()</td>
                  <td>@Model.Items[i].Quantity</td>
                  <td>
                      <a asp-action="Delete" asp-controller="OrderItem" asp-route-id="@Model.Items[i].Id" class="btn btn-danger">Delete</a>
                  </td>
                </tr>
        }
      </tbody>
    </table>

G1/PizzaApp/PizzaWebApp/PizzaWebApp/Views/Order/Index.cshtml
@using System.Globalization;
@model List<OrderViewModel>

<a asp-action="CreateOrder" class="btn btn-primary">Add new</a>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Address</th>
      <th scope="col">PhoneNumber</th>
      <th scope="col">Items</th>
      <th scope="col">Note</th>
      <th scope="col">Total Price</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
        @for (var i = 0; i < Model.Count; i++)
        {            
                <tr>
                  <th scope="row">@(i + 1)</th>
                  <td>@Model[i].Address</td>
                  <td>@Model[i].PhoneNumber</td>
                  <td>
                      <ul>
                        @foreach(var item in Model[i].Items)
                        {
                            <li>
                                @item.MenuItem.ToString() x @item.Quantity
                            </li>
                        }
                    </ul>
                  </td>
                  <td>@Model[i].Note</td>
                  <td>@Model[i].TotalPrice.ToString("C", CultureInfo.CreateSpecificCulture("mk-MK"))</td>
                  <td>
                      <a asp-action="Details" asp-route-id="@Model[i].Id" class="btn btn-primary">Details</a>
                      <a asp-action="Delete" asp-route-id="@Model[i].Id" class="btn btn-danger">Delete</a>
                  </td>
                </tr>
        }
      </tbody>
    </table>